version: '3'
services:

  subjects_service:
    build: ./subjects-service
    container_name: subjects-service
    ports:
      - "8001:8001"
    # environment:
    #   - SOME_ENV=VALUE

  tests_service:
    build: ./tests-service
    container_name: tests-service
    ports:
      - "8002:8002"
    depends_on:
      - subjects-service

  questions_service:
    build: ./questions-service
    container_name: questions-service
    ports:
      - "8003:8003"
    depends_on:
      - tests-service

  students_service:
    build: ./students-service
    container_name: students-service
    ports:
      - "8004:8004"

  answers_service:
    build: ./answers-service
    container_name: answers-service
    ports:
      - "8005:8005"
    depends_on:
      - questions-service
      - students-service
  redis:
    image: "redis:7"
    container_name: redis-container
    ports:
      - "6379:6379"